### PR TITLE
Support multi_json for body parsers

### PR DESCRIPTION
**Pull request by jodosha**
Closes #105

### CODE REVIEW

**Comment by Erol** [comment]
I like it! Just not too comfortable with `JSON` masquerading as `MultiJson`, but other than that this works for me.

**Comment by Erol** [comment]
How about this @jodosha? This way our mock `MultiJson` is scoped inside `JsonParser`:

```ruby
begin
  require 'multi_json'
rescue LoadError
  require 'json'
end

module Hanami
  module Routing
    module Parsing
      class JsonParser < Parser
        unless defined? MultiJson
          MultiJson = JSON
          MultiJson::ParseError = JSON::ParserError
        end

        ...
      end
    end
  end
end
```

**Comment by jodosha** [comment]
@Erol Now we're talking! 😉  Your suggestion is better. 👍

**Comment by Erol** [comment]
Sweet! 👍

**Pull request merged**
