### PR TITLE
Don't parse request body when Body Parser already parsed it

### PR DESCRIPTION
**Pull request by jodosha**
Fixes https://github.com/hanami/router/issues/237

### CODE REVIEW

**Comment by wuarmin** [comment]
@jodosha do you saw my review?

**Comment by wuarmin** [comment]
@jodosha Do you saw my review?

I tested this branch. A JSON payload is now parsed accordingly if the json-body parser is set.
So following...
```console
curl -X POST http://localhost:2300/upload -H 'Content-Type: application/json' -d '{"foo": "%bar"}'
```
...works.
Following...
But we're still missing a `multipart/form-data` parser, aren't we? 
```console
curl -F 'file=@/tmp/1.json' http://localhost:2300/upload
```
fails with 
```txt
Rack::QueryParser::InvalidParameterError: invalid %-encoding
```
I think we should open an issue regarding the `multipart/form-data`-parsing.

**Comment by jodosha** [comment]
@wuarmin I can reproduce the problem with the following cURL command:

```shell
⚡ curl -X POST http://localhost:2300/upload \
   --header 'Content-Type: multipart/form-data; boundary=---------AaB03x' \
   --data-binary @./tmp/1.json
```

👉 But using `::Rack::Multipart.parse_multipart(env)` gives me this exception:

```shell
2022-11-18 09:35:12 +0100 Rack app ("POST /upload" - (127.0.0.1)): #<EOFError: EOFError>
```

This is `tmp/1.json`

```json
{"foo": "%bar"}
```

```ruby
# frozen_string_literal: true

require "hanami"
require "hanami/middleware/body_parser"

module Bookshelf
  class App < Hanami::App
    config.middleware.use Hanami::Middleware::BodyParser, :json
  end
end
```

```
# frozen_string_literal: true

module Bookshelf
  class Routes < Hanami::Routes
    post "/upload", to: "upload.create"
  end
end
```

```
# frozen_string_literal: true

module Bookshelf
  module Actions
    module Upload
      class Create < Bookshelf::Action
        def handle(req, res)
          res.body = req.params.to_h
        end
      end
    end
  end
end
```

**Comment by wuarmin** [comment]
@jodosha thanks for reproducing!
I observed the same thing in my spec approach in #239 

```ruby
  context "file upload" do
    def multipart_fixture(name, boundary = "AaB03x")
      file = fixture_path(name)
      data = File.open(file, 'rb') { |io| io.read }
  
      type = %(multipart/form-data; boundary=#{boundary})
      length = data.size
  
      { "CONTENT_TYPE" => type,
        "CONTENT_LENGTH" => length.to_s,
        :input => StringIO.new(data) }
    end

    fit "should handle a file upload" do
      env = Rack::MockRequest.env_for(
        "/submit",
        multipart_fixture("foo.xml").merge(method: "POST"),
      )

      subject.call(env)

      puts env["router.params"]
    end
  end
```
I got an `<EOFError`. But I think this is not a rack bug. If I upload the file via...
```console
curl -F 'file=@/tmp/1.json' http://localhost:2300/upload
```
`Rack::Multipart.parse_multipart(env)' works perfectly.
I use the fix-branch(#239) in a prod-project and have no issues with file uploads. So I think it's more an issue with our testing approach (my spec approach, your cURL test) than a rack bug.

**Comment by jodosha** [comment]
@wuarmin 
> WDYT about a built-in parser for this mimetype?

Yes. It's a good idea.

**Comment by jodosha** [comment]
@wuarmin A couple of notes on reproducing this bug:

* I can't reproduce with your cURL command, that's why I had to try with a different cURL approach.
* I can't reproduce the problem in a way you did in #239 
  * See this [spec](https://github.com/hanami/router/blob/d329a03277fb80bb027170306f879801aa739555/spec/integration/hanami/router/params_spec.rb#L48) in `main` branch, it contains `"%"` char and it doesn't crash.

**Comment by jodosha** [comment]
@wuarmin 
Could you please dump here the Rack env that you get with this cURL command?

```shell
curl -F 'file=@/tmp/1.json' http://localhost:2300/upload
```

---

I'm stuck with a spec that crashes with `EOFError`

**Comment by jodosha** [comment]
@wuarmin I tried to debug Rack and it tries to read twice the IO input.
The first it time succeeds, the second time it fails because there is no input left in IO.

It shouldn't read the second time, as the input is consumed at the first attempt: my file is 96 bytes and the buffer size is ~1Mb.

**Comment by wuarmin** [comment]
@jodosha 
To reproduce the issue with my command, the input of the file has to be:
```json
{"foo": "100% bar"}
```
or 
```json
{"foo": "% bar"}
```
The input, you used
```json
{"foo": "%bar"}
```
works for me too. Very strange.

Here's the env you requested:
```txt
{
              "rack.version" => [
        [0] 1,
        [1] 6
    ],
               "rack.errors" => #<IO:<STDERR>>,
          "rack.multithread" => true,
         "rack.multiprocess" => true,
             "rack.run_once" => false,
           "rack.url_scheme" => "http",
               "SCRIPT_NAME" => "",
              "QUERY_STRING" => "",
           "SERVER_SOFTWARE" => "puma 6.0.0 Sunflower",
         "GATEWAY_INTERFACE" => "CGI/1.2",
            "REQUEST_METHOD" => "POST",
              "REQUEST_PATH" => "/upload",
               "REQUEST_URI" => "/upload",
           "SERVER_PROTOCOL" => "HTTP/1.1",
                 "HTTP_HOST" => "localhost:2300",
           "HTTP_USER_AGENT" => "curl/7.58.0",
               "HTTP_ACCEPT" => "*/*",
            "CONTENT_LENGTH" => "221",
              "CONTENT_TYPE" => "multipart/form-data; boundary=------------------------d476dcad10bef8a1",
    "puma.request_body_wait" => 0.09569099999498576,
               "SERVER_NAME" => "localhost",
               "SERVER_PORT" => "2300",
                 "PATH_INFO" => "/hotel_notifications/notifications/upload",
               "REMOTE_ADDR" => "192.168.32.1",
              "HTTP_VERSION" => "HTTP/1.1",
               "puma.socket" => #<TCPSocket:fd 17, AF_INET, 192.168.32.4, 2300>,
              "rack.hijack?" => true,
               "rack.hijack" => #<Puma::Client:0x1644 @ready=true>,
                "rack.input" => #<StringIO:0x00007f44a86bff78>,
          "rack.after_reply" => [],
               "puma.config" => #<Puma::Configuration:0x00007f44a8579b28 @options=#<Puma::UserFileDefaultOptions:0x00007f44a8579650 @user_options={:environment=>"development", :log_requests=>false, :control_url=>"tcp://localhost:9293", :control_auth_token=>"7243f665910b079b7676f2fd2e514ef9", :log_writer=>#<Puma::LogWriter:0x00007f44a857a1e0 @formatter=#<Puma::LogWriter::PidFormatter:0x00007f44a8554828>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @debug=false, @error_logger=#<Puma::ErrorLogger:0x00007f44a857a0a0 @ioerr=#<IO:<STDERR>>, @debug=false>>, :logger=>#<Puma::LogWriter:0x00007f44a857a1e0 @formatter=#<Puma::LogWriter::PidFormatter:0x00007f44a8554828>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @debug=false, @error_logger=#<Puma::ErrorLogger:0x00007f44a857a0a0 @ioerr=#<IO:<STDERR>>, @debug=false>>}, @file_options={:config_files=>["config/puma.rb"], :min_threads=>5, :max_threads=>5, :binds=>["tcp://0.0.0.0:2300"], :environment=>"development", :workers=>2, :before_worker_boot=>[#<Proc:0x00007f44a8550110 config/puma.rb:11>], :preload_app=>true}, @default_options={:auto_trim_time=>30, :binds=>["tcp://0.0.0.0:9292"], :clean_thread_locals=>false, :debug=>false, :early_hints=>nil, :environment=>"development", :first_data_timeout=>30, :io_selector_backend=>:auto, :log_requests=>false, :logger=>#<IO:<STDOUT>>, :max_fast_inline=>10, :max_threads=>5, :min_threads=>0, :mode=>:http, :mutate_stdout_and_stderr_to_sync_on_write=>true, :out_of_band=>[], :persistent_timeout=>20, :queue_requests=>true, :rackup=>"config.ru", :raise_exception_on_sigterm=>true, :reaping_time=>1, :remote_address=>:socket, :silence_single_worker_warning=>false, :tag=>"app", :tcp_host=>"0.0.0.0", :tcp_port=>9292, :wait_for_less_busy_worker=>0.005, :worker_boot_timeout=>60, :worker_check_interval=>5, :worker_culling_strategy=>:youngest, :worker_shutdown_timeout=>30, :worker_timeout=>60, :workers=>0, :preload_app=>false}>, @plugins=#<Puma::PluginLoader:0x00007f44a8579588 @instances=[]>, @user_dsl=#<Puma::DSL:0x00007f44a8579448 @config=#<Puma::Configuration:0x00007f44a8579b28 ...>, @options={:environment=>"development", :log_requests=>false, :control_url=>"tcp://localhost:9293", :control_auth_token=>"7243f665910b079b7676f2fd2e514ef9", :log_writer=>#<Puma::LogWriter:0x00007f44a857a1e0 @formatter=#<Puma::LogWriter::PidFormatter:0x00007f44a8554828>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @debug=false, @error_logger=#<Puma::ErrorLogger:0x00007f44a857a0a0 @ioerr=#<IO:<STDERR>>, @debug=false>>, :logger=>#<Puma::LogWriter:0x00007f44a857a1e0 @formatter=#<Puma::LogWriter::PidFormatter:0x00007f44a8554828>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @debug=false, @error_logger=#<Puma::ErrorLogger:0x00007f44a857a0a0 @ioerr=#<IO:<STDERR>>, @debug=false>>}, @plugins=[]>, @file_dsl=#<Puma::DSL:0x00007f44a8579308 @config=#<Puma::Configuration:0x00007f44a8579b28 ...>, @options={:config_files=>["config/puma.rb"], :min_threads=>5, :max_threads=>5, :binds=>["tcp://0.0.0.0:2300"], :environment=>"development", :workers=>2, :before_worker_boot=>[#<Proc:0x00007f44a8550110 config/puma.rb:11>], :preload_app=>true}, @plugins=[], @path="config/puma.rb">, @default_dsl=#<Puma::DSL:0x00007f44a8579240 @config=#<Puma::Configuration:0x00007f44a8579b28 ...>, @options={:auto_trim_time=>30, :binds=>["tcp://0.0.0.0:9292"], :clean_thread_locals=>false, :debug=>false, :early_hints=>nil, :environment=>"development", :first_data_timeout=>30, :io_selector_backend=>:auto, :log_requests=>false, :logger=>#<IO:<STDOUT>>, :max_fast_inline=>10, :max_threads=>5, :min_threads=>0, :mode=>:http, :mutate_stdout_and_stderr_to_sync_on_write=>true, :out_of_band=>[], :persistent_timeout=>20, :queue_requests=>true, :rackup=>"config.ru", :raise_exception_on_sigterm=>true, :reaping_time=>1, :remote_address=>:socket, :silence_single_worker_warning=>false, :tag=>"app", :tcp_host=>"0.0.0.0", :tcp_port=>9292, :wait_for_less_busy_worker=>0.005, :worker_boot_timeout=>60, :worker_check_interval=>5, :worker_culling_strategy=>:youngest, :worker_shutdown_timeout=>30, :worker_timeout=>60, :workers=>0, :preload_app=>false}, @plugins=[]>>,
             "router.params" => {}
}
```

**Comment by jodosha** [comment]
@wuarmin At this point I believe it's either:

1. Us not testing the feature well (both with RSpec and cURL)
2. A Rack bug

See this example that uses Rack only: https://gist.github.com/jodosha/27b53ddadc7218b2bd6e0a9490045793

What do you think?

**Comment by wuarmin** [comment]
@jodosha I tried to fix the failing spec, by using `Rack::Multipart.build_multipart`. Please see my review at #242.

**Pull request merged**
